image: docker:latest

stages:
  - build
  - test

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

job_build_a_la_sauce_docker:
  stage: build
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

htmlvalidator:
  stage: test
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker run --rm -v /websitefiles:/websitefiles $IMAGE_TAG cp -r /reveal.js /websitefiles
    - docker run --rm -v /websitefiles:/websitefiles validator/validator java -jar ./vnu.jar --skip-non-html --errors-only /websitefiles/index.html