stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
  stage: build
  image: docker:stable-dind
  script:
    - echo "Logging to GitLab Container Registry with CI credentials..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build --tag $IMAGE_TAG .
    - docker push $IMAGE_TAG

production:
  stage: deploy
  environment:
    name: production
    url: https://meetup-docker-ci-cd.slides.enix.io
  only:
    refs:
      - master
  image: dtzar/helm-kubectl:2.13.1
  before_script:
    - apk add --no-cache jq
  script:
    - kubectl version
    - helm version
    - export DOCKER_REGISTRY_SECRET=$(kubectl create secret -n slides-enix-io docker-registry bla --docker-server=$CI_REGISTRY --docker-username="${CI_DEPLOY_USER}" --docker-password="${CI_DEPLOY_PASSWORD}" -o json --dry-run | jq '.data.".dockerconfigjson"')
    - helm upgrade --install --wait --set image=$IMAGE_TAG $CI_PROJECT_NAME --set imagePullSecret.value="$DOCKER_REGISTRY_SECRET" chart/
