stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
  stage: build
  image: docker:stable-dind
  script:
    - echo "Logging to GitLab Container Registry with CI credentials..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build --tag $IMAGE_TAG .
    - docker push $IMAGE_TAG

production:
  stage: deploy
  environment:
    name: production
    url: https://meetup-docker-ci-cd.slides.enix.io
  only:
    refs:
      - master
  image: dtzar/helm-kubectl:2.13.1
  script:
    - kubectl version
    - helm version
    - helm upgrade --install --set image=$IMAGE_TAG $CI_PROJECT_NAME chart/
