version: '3.4'
services:
  www:
    image: ${IMAGE_TAG:-meetup-docker-ci-cd}
    build:
      context: .
      target: develop
    restart: always
    volumes:
    - "./www/index.html:/reveal.js/index.html"
    - "./www/enix.css:/reveal.js/enix.css"